name: React CI Unit Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  APP_DIR: my-app

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23'

      - name: Install dependencies
        run: npm install
        working-directory: ${{ env.APP_DIR }}

      - name: Run Tests
        run: npm test -- --watchAll=false
        working-directory: ${{ env.APP_DIR }}
